### PR TITLE
update: participant feedbacks to advanced to show image for the combined states

### PR DESCRIPTION
**Pull request by digitaldrummerj**
fixes: #98

### CODE REVIEW

**Comment by digitaldrummerj** [comment]
I wanted to give you a preview of what I worked on for the feedback to show all of the particiapant's active states in an image (mic live, camera on, active speaker, and hand raised).  Figured it would be good to get another set of eyes looking at it.  

I tested it on an event with 160 people and it worked great but there was not a lot of switching active speaker or hand raising.  I have an event coming up on May 9th that should have over 100 people on it and there will be a lot more switching of the active speaker switching and hand raising.

**Comment by digitaldrummerj** [comment]
Example of what the feedback looks like.  

image

**Comment by JeffreyDavidsz** [comment]
I think you are on the right track, not sure if finding people is still easy to do, def need the icons not only the color.

**Comment by JeffreyDavidsz** [comment]
@digitaldrummerj are you ok, to swap this from draft to ready?

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz it is ready for review.  I tested it out on an event today with over 100 people and it worked great for gallery, groups, participants, and select by name.

**Review by JeffreyDavidsz — APPROVED** [review]

**Pull request merged**
